### ISSUE TITLE
Open Source Licence

### ISSUE THREAD

**Issue by lexbailey** [tmarkettos/gccspirit-lasercutter-pythondriver#1]
Hi,
I've forked this repo so that I could fix some issues with running on linux.
I might want to package this or something derived from it, and would like to know what licence to use.

Would you mind specifying a licence in the repository?

Thanks :)

**Comment by tmarkettos** [comment]
Hello...

All the Python files already have BSD licence headers.  The CAM files are generated by Eagle so will be under whatever licence Eagle puts on them. The .SGX files are generated by the GCC Windows printer driver so will be under whatever licence GCC puts on them.  

Because those last two types of files don't (obviously) accept comments I haven't put any notice or licence header on them, nor have I researched the licence the original tools came under, but it could be argued they are purely descriptive with no creative content in their expression and hence not copyrightable.

So the actual code is BSD licensed but other pieces I can't make a strong statement about, and is up to the user to satisfy themselves the others are not copyrightable.

**Comment by lexbailey** [comment]
awesome! thanks for the quick reply 😊
